### ISSUE TITLE
package version issue

### ISSUE THREAD

**Issue by butterywombat** [rotundasoftware/path-mapper#2]
@dgbeck Hi I'm trying to use version 0.1.3 but the published npm module looks like it's from 0.1.1 (without the 'small bug fix' commit change) so this is causing issues in cartero when the asset is not found (compares '' to '/') cc: @ferlores

**Comment by dgbeck** [comment]
Hi @dxuehu , thanks for the heads up! I just published 0.1.4. Closing for now but let me know if you continue to have problems.

**Comment by butterywombat** [comment]
🎉thanks!

**Comment by butterywombat** [comment]
Hmm I still can't get the latest version (with npm install) although I see the new version on npm. Weird or maybe it takes awhile?

```
npm install path-mapper@0.1.4
npm WARN package.json cartero-node-hook@1.1.0 No license field.
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "asdfasdfasd/bin/npm" "install" "path-mapper@0.1.4"
npm ERR! node v0.12.7
npm ERR! npm  v2.13.5

npm ERR! version not found: path-mapper@0.1.4
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /node_modules/cartero-node-hook/npm-debug.log

npm install path-mapper@0.1.3
npm WARN package.json cartero-node-hook@1.1.0 No license field.
path-mapper@0.1.3 node_modules/path-mapper
```

**Comment by dgbeck** [comment]
Hi @dxuehu ,

Strange, I can't reproduce 

```
cartero git:(master) ✗ npm install path-mapper@0.1.4
path-mapper@0.1.4 node_modules/path-mapper
cartero git:(master) ✗
```

Reopening, not sure how to debug this one though. Maybe try form a different machine?

**Comment by butterywombat** [comment]
Hmm weird. I was able to install it on another machine. Will look more closely tomorrow, maybe it has something to do with our artifactory, thanks!

**Comment by butterywombat** [comment]
@dgbeck Oh I think I was confused--the published version is probably right. See https://github.com/rotundasoftware/path-mapper/commit/d6b2002b4e16528b588da5ed95a6c5a4c0e3f95c#diff-168726dbe96b3ce427e7fedce31bb0bcR9

**Comment by dgbeck** [comment]
Hm, I'm not sure why that test was removed. The intention might have been to remove the other half of the test, since I don't think that one is ever used. Fixed in v0.1.5, just published. Let's see if this time it works for you! Closing again...

**Comment by butterywombat** [comment]
looks great, thanks!!
